FROM ubuntu:16.04


MAINTAINER mahesh <mahesh.rockz790@gmail.com>


RUN apt-get update

RUN apt-get install -y default-jdk tomcat7


ENV CATALINA_HOME /usr/share/tomcat7

ENV CATALINA_BASE /var/lib/tomcat7

ENV CATALINA_PID  /var/lib/tomcat7.pid

ENV CATALINA_SH /usr/share/tomcat7/bin/catalina.sh

ENV CATALINA_TMDIR 


EXPOSE 80


ENTRYPOINT []
